# Generated by Django 3.2 on 2024-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240329_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='OTP-code'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP creation time'),
        ),
    ]
